name: Backup Multiple Open Source Projects
on:
  schedule:
    - cron: '0 */2 * * *'  # 每天凌晨运行一次，可以根据需要调整此时间表达式
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository QxScript
        uses: actions/checkout@v2
        with:
          repository: xiaomaoJT/QxScript
          path: source-QxScript
      - name: Checkout source repository ios_rule_script
        uses: actions/checkout@v2
        with:
          repository: blackmatrix7/ios_rule_script
          path: source-ios_rule_script
      - name: Checkout target backup repository
        uses: actions/checkout@v2
        with:
          repository: wangyuyan666/QuanxBackup
          path: backup
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的令牌
      - name: Copy QxScript to backup directory
        run: cp -r source-QxScript/. backup/QxScript/
      - name: Copy ios_rule_script to backup directory
        run: cp -r source-ios_rule_script/. backup/ios_rule_script/
      - name: Commit and push changes
        run: |
          cd backup
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          git push
