name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          repository: wangyuyan666/QuanxBackup
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Clone QxScript Repository
        run: |
          rm -rf QxScript  
          git clone --depth=1 https://github.com/xiaomaoJT/QxScript
          rm -rf QxScript/.git # 删除 git 文件夹以避免冲突

      - name: Clone ios_rule_script Repository
        run: |
          rm -rf ios_rule_script
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script
          rm -rf ios_rule_script/.git  # 删除 git 文件夹以避免冲突

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
