name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Clone QxScript Repository
        run: |
          git clone --depth=1 https://github.com/xiaomaoJT/QxScript xiaomaoJT_QxScript
          rm -rf "QxScript(xiaomaoJT)"
          mkdir -p "QxScript(xiaomaoJT)"
          mv xiaomaoJT_QxScript/* "QxScript(xiaomaoJT)/"
          rm -rf xiaomaoJT_QxScript

      - name: Clone ios_rule_script Repository
        run: |
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script blackmatrix7_ios_rule_script
          rm -rf "ios_rule_script(blackmatrix7)"
          mkdir -p "ios_rule_script(blackmatrix7)"
          mv blackmatrix7_ios_rule_script/* "ios_rule_script(blackmatrix7)/"
          rm -rf blackmatrix7_ios_rule_script

      - name: Clone ios_rule_script Repository
        run: |
          git clone --depth=1 https://github.com/NobyDa/Script NobyDa_Script
          rm -rf "Script(NobyDa)"
          mkdir -p "Script(NobyDa)"
          mv NobyDa_Script/* "Script(NobyDa)/"
          rm -rf NobyDa_Script    

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/wangyuyan666/QuanxBackup.git
          git push --force origin main
