name: Backup Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行一次
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          repository: wangyuyan666/QuanxBackup
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Clone QxScript Repository
        run: |
          pwd
          git clone --depth=1 https://github.com/xiaomaoJT/QxScript QxScript
          rm -rf QxScript/.git  # 删除 git 文件夹以避免冲突
          mv QxScript/* .
          rm -rf QxScript  # 清理临时文件夹
          pwd

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/wangyuyan666/QuanxBackup.git
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
