name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Clone QxScript Repository
        run: |
          rm -rf QxScript
          git clone --depth=1 https://github.com/xiaomaoJT/QxScript QxScript

      - name: Clone ios_rule_script Repository
        run: |
          rm -rf ios_rule_script
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script ios_rule_script

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/wangyuyan666/QuanxBackup.git
          git push origin main
